# Variables
variables:
  # Any variables defined in GitLab Project CI/CD Settings

# Define the stages for your pipeline
stages:
  - test

# Define the job for running Playwright tests
run_tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.41.1-jammy
  script:
    - npm ci # Install project dependencies
    - npx playwright test # Run your Playwright tests
    - echo "https://$CI_PROJECT_NAMESPACE.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/playwright-report/index.html" # print the URL to view the results
  allow_failure: true

  # Publish Playwright test results as artifacts and keep for 7 days
artifacts:
  when: always
  paths:  
    - playwright-report/
    - test-results/
  expire_in: 7 days